[tool.poetry]
name = "lpp"
version = "0.1.0"
description = ""
authors = ["Ruslan <ruslan15-mol@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.23.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
